-- 현재 소스 기준 Oracle 신규 설치용 애플리케이션 스키마 (9개 테이블).
-- app.jpa.table-prefix 기본값(MY_) 기준. 변경 시 테이블명을 함께 변경한다.
-- 빈 스키마에 한 번만 실행한다. 기존 DB 업그레이드는 db/migration을 사용한다.
-- 이 파일로 신규 생성한 DB에는 과거 마이그레이션을 다시 적용하지 않는다.
-- Quartz 테이블은 db_quartz.sql로 별도 생성한다.
-- local 프로필(H2)은 JPA create-drop 및 Quartz 자동 초기화를 사용한다.
CREATE TABLE MY_SCHEDULE_INFO (
    TENANT_ID VARCHAR2(14) NOT NULL,
    SCHEDULE_GROUP VARCHAR2(50) NOT NULL,
    SCHEDULE_NAME VARCHAR2(200) NOT NULL,
    SCHEDULE_TYPE VARCHAR2(20) NOT NULL,
    JOB_TYPE VARCHAR2(20) NOT NULL,
    JOB_ID VARCHAR2(100),

    CRON_EXPRESSION VARCHAR2(120) NOT NULL,
    COMMAND VARCHAR2(200) NOT NULL,
    PARAMETERS CLOB,
    DEPENDS_ON CLOB,
    MISFIRE_POLICY VARCHAR2(20) DEFAULT 'FIRE_ONCE' NOT NULL,
    DESCRIPTION VARCHAR2(255),

    SCHEDULE_START_TIME TIMESTAMP,
    SCHEDULE_END_TIME TIMESTAMP,

    USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,

    REG_USER_ID VARCHAR2(50) DEFAULT 'SYSTEM', -- createdBy
    MODIFY_USER_ID VARCHAR2(50), -- updatedBy
    REG_OCCUR_DTTM VARCHAR2(23) NOT NULL, -- createdAt
    MODIFY_OCCUR_DTTM VARCHAR2(23), -- updatedAt

    CONSTRAINT PK_MY_SCHEDULE_INFO PRIMARY KEY (TENANT_ID, SCHEDULE_GROUP, SCHEDULE_NAME)
);

-- 추가
CREATE TABLE MY_SCHEDULE_SKIP_INFO (
   TENANT_ID VARCHAR2(14) NOT NULL,
   SCHEDULE_GROUP VARCHAR2(50) NOT NULL,
   SCHEDULE_NAME VARCHAR2(200) NOT NULL,

   SKIP_TIME TIMESTAMP NOT NULL,

   REG_USER_ID VARCHAR2(50) DEFAULT 'SYSTEM',
   MODIFY_USER_ID VARCHAR2(50),
   REG_OCCUR_DTTM VARCHAR2(23) NOT NULL,
   MODIFY_OCCUR_DTTM VARCHAR2(23),

   CONSTRAINT PK_MY_SCHEDULE_SKIP_INFO PRIMARY KEY (TENANT_ID, SCHEDULE_GROUP, SCHEDULE_NAME, SKIP_TIME)
);

CREATE TABLE MY_SCHEDULE_EXECUTION_HISTORY (
    EXECUTION_ID VARCHAR2(36) NOT NULL,
    OCCURRENCE_KEY VARCHAR2(200),
    SCHEDULED_AT TIMESTAMP WITH TIME ZONE,
    ATTEMPT_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    CANCELLATION_REQUESTED VARCHAR(1) DEFAULT 'N' NOT NULL,
    VERSION NUMBER(19) DEFAULT 0 NOT NULL,
    RETRY_WAIT_SINCE TIMESTAMP WITH TIME ZONE,
    TENANT_ID VARCHAR2(14) NOT NULL,
    SCHEDULE_GROUP VARCHAR2(50) NOT NULL,
    SCHEDULE_NAME VARCHAR2(200) NOT NULL,
    FIRE_INSTANCE_ID VARCHAR2(100),
    TRIGGER_NODE_ID VARCHAR2(100),
    SCHEDULE_TYPE VARCHAR2(20) NOT NULL,
    EXECUTION_COUNT NUMBER(19) DEFAULT 0 NOT NULL,
    JOB_TYPE VARCHAR2(20) NOT NULL,
    JOB_ID VARCHAR2(100),
    CRON_EXPRESSION VARCHAR2(120) NOT NULL,
    COMMAND VARCHAR2(200) NOT NULL,
    PARAMETERS CLOB,
    STATUS VARCHAR2(20) NOT NULL,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    DURATION NUMBER(19),
    MESSAGE CLOB,
    CONSTRAINT PK_MY_SCHEDULE_EXECUTION_HISTORY PRIMARY KEY (EXECUTION_ID),
    CONSTRAINT UK_MY_HISTORY_OCCURRENCE UNIQUE (TENANT_ID, SCHEDULE_GROUP, SCHEDULE_NAME, OCCURRENCE_KEY)
);

CREATE INDEX IDX_MY_SCHED_EXEC_FIRE_ID ON MY_SCHEDULE_EXECUTION_HISTORY (FIRE_INSTANCE_ID);
CREATE INDEX IX_HISTORY_WAIT_FIFO ON MY_SCHEDULE_EXECUTION_HISTORY (STATUS, SCHEDULED_AT, EXECUTION_ID);

-- 실행권 및 프로세스 시도 기록
CREATE TABLE MY_BATCH_EXECUTION_LEASE (
    EXECUTION_ID VARCHAR2(36) PRIMARY KEY,
    OWNER_NODE VARCHAR2(100),
    LEASE_TOKEN NUMBER(19) DEFAULT 0 NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    VERSION NUMBER(19) DEFAULT 0 NOT NULL
);

CREATE TABLE MY_BATCH_ATTEMPT (
    ATTEMPT_ID VARCHAR2(64) PRIMARY KEY,
    EXECUTION_ID VARCHAR2(36) NOT NULL,
    ATTEMPT_NO NUMBER(10) NOT NULL,
    NODE_ID VARCHAR2(100) NOT NULL,
    WORKER_NODE_ID VARCHAR2(100),
    LEASE_TOKEN NUMBER(19) NOT NULL,
    PID NUMBER(19),
    STARTED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PROCESS_STARTED_AT TIMESTAMP WITH TIME ZONE,
    ENDED_AT TIMESTAMP WITH TIME ZONE,
    EXIT_CODE NUMBER(10),
    STATUS VARCHAR2(32) NOT NULL,
    FAILURE_REASON VARCHAR2(1000),
    HEARTBEAT_AT TIMESTAMP WITH TIME ZONE,
    PROCESS_LAUNCH_STATE VARCHAR2(20) DEFAULT 'UNKNOWN' NOT NULL,
    CONSTRAINT UK_MY_ATTEMPT_NO UNIQUE (EXECUTION_ID, ATTEMPT_NO)
);

-- 시도별 복구 판정 이력 (기존 마이그레이션의 FK/유일 제약 포함)
CREATE TABLE MY_BATCH_RECONCILIATION (
    RECONCILIATION_ID VARCHAR2(36) NOT NULL,
    EXECUTION_ID VARCHAR2(36) NOT NULL,
    ATTEMPT_ID VARCHAR2(64) NOT NULL,
    RESULT VARCHAR2(20) NOT NULL,
    REASON CLOB NOT NULL,
    RECONCILED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT PK_RECONCILIATION PRIMARY KEY (RECONCILIATION_ID),
    CONSTRAINT UK_RECONCILIATION_ATTEMPT UNIQUE (EXECUTION_ID, ATTEMPT_ID),
    CONSTRAINT FK_RECONCILIATION_HISTORY FOREIGN KEY (EXECUTION_ID)
        REFERENCES MY_SCHEDULE_EXECUTION_HISTORY(EXECUTION_ID),
    CONSTRAINT FK_RECONCILIATION_ATTEMPT FOREIGN KEY (ATTEMPT_ID)
        REFERENCES MY_BATCH_ATTEMPT(ATTEMPT_ID)
);

CREATE TABLE MY_BATCH_NODE (
    NODE_ID VARCHAR2(100) PRIMARY KEY,
    STATUS VARCHAR2(20) NOT NULL CHECK (STATUS IN ('ACTIVE', 'DRAINING', 'OFFLINE')),
    LAST_HEARTBEAT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    STARTED_AT TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    INSTANCE_ID VARCHAR2(36) NOT NULL,
    DRAIN_REQUESTED NUMBER(1) NOT NULL CHECK (DRAIN_REQUESTED IN (0, 1))
);

CREATE TABLE MY_BATCH_DEPENDENCY_GRAPH_LOCK (
    LOCK_ID VARCHAR2(20) PRIMARY KEY
);
INSERT INTO MY_BATCH_DEPENDENCY_GRAPH_LOCK (LOCK_ID) VALUES ('GLOBAL');

CREATE TABLE MY_BATCH_EXECUTION_DEPENDENCY (
    EXECUTION_ID VARCHAR2(36) PRIMARY KEY,
    DEPENDS_ON CLOB NOT NULL,
    BUSINESS_OCCURRENCE_KEY VARCHAR2(150),
    OCCURRENCE_REASON VARCHAR2(500)
);

COMMIT;

