--* table

-- application.yml의 app.jpa.table-prefix 기본값(MY_) 기준 참고 DDL
CREATE TABLE MY_SCHEDULE_INFO (
    TENANT_ID VARCHAR2(14) NOT NULL,
    SCHEDULE_GROUP VARCHAR2(50) NOT NULL,
    SCHEDULE_NAME VARCHAR2(200) NOT NULL,
    SCHEDULE_TYPE VARCHAR2(20) NOT NULL,
    JOB_TYPE VARCHAR2(20) NOT NULL,
    JOB_ID VARCHAR2(100) NOT NULL,

    CRON_EXPRESSION VARCHAR2(120) NOT NULL,
    COMMAND VARCHAR2(200) NOT NULL,
    PARAMETERS CLOB,
    DESCRIPTION VARCHAR2(255),

    SCHEDULE_START_TIME TIMESTAMP,
    SCHEDULE_END_TIME TIMESTAMP,

    USE_YN VARCHAR2(1) DEFAULT 'Y',

    REG_USER_ID VARCHAR2(50) DEFAULT 'SYSTEM', -- createdBy
    MODIFY_USER_ID VARCHAR2(50), -- updatedBy
    REG_OCCUR_DTTM VARCHAR2(23) NOT NULL, -- createdAt
    MODIFY_OCCUR_DTTM VARCHAR2(23), -- updatedAt

    CONSTRAINT PK_MY_SCHEDULE_INFO PRIMARY KEY (TENANT_ID, SCHEDULE_GROUP, SCHEDULE_NAME)
);

-- 추가
CREATE TABLE MY_SCHEDULE_SKIP_INFO (
   TENANT_ID VARCHAR2(14) NOT NULL,
   SCHEDULE_GROUP VARCHAR2(50) NOT NULL,
   SCHEDULE_NAME VARCHAR2(200) NOT NULL,

   SKIP_TIME TIMESTAMP,

   REG_USER_ID VARCHAR2(50) DEFAULT 'SYSTEM',
   MODIFY_USER_ID VARCHAR2(50),
   REG_OCCUR_DTTM VARCHAR2(23) NOT NULL,
   MODIFY_OCCUR_DTTM VARCHAR2(23),

   CONSTRAINT PK_MY_SCHEDULE_SKIP_INFO PRIMARY KEY (TENANT_ID, SCHEDULE_GROUP, SCHEDULE_NAME, SKIP_TIME)
);

CREATE TABLE MY_SCHEDULE_EXECUTION_HISTORY (
    TENANT_ID       VARCHAR2(14) NOT NULL,
    SCHEDULE_GROUP  VARCHAR2(50) NOT NULL,
    SCHEDULE_NAME   VARCHAR2(200) NOT NULL,

    FIRE_INSTANCE_ID VARCHAR2(100),
    SCHEDULE_TYPE   VARCHAR2(20) NOT NULL,
    EXECUTION_COUNT NUMBER(19) DEFAULT '1',

    JOB_TYPE VARCHAR2(20) NOT NULL,
    JOB_ID VARCHAR2(100),

    CRON_EXPRESSION VARCHAR2(120) NOT NULL,
    COMMAND VARCHAR2(200) NOT NULL,
    PARAMETERS CLOB,

    STATUS VARCHAR2(20) NOT NULL,

    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    DURATION NUMBER(19),
    MESSAGE CLOB,

    CONSTRAINT PK_MY_SCHEDULE_EXECUTION_HISTORY PRIMARY KEY (TENANT_ID, SCHEDULE_GROUP, SCHEDULE_NAME, START_TIME)

);

CREATE INDEX IDX_MY_SCHED_EXEC_FIRE_ID ON MY_SCHEDULE_EXECUTION_HISTORY (FIRE_INSTANCE_ID);

-- Phase 1: app.jpa.table-prefix 기본값(MY_) 기준. 기존 테이블 데이터는 변경하지 않는다.
CREATE TABLE MY_BATCH_EXECUTION (
    EXECUTION_ID VARCHAR2(36) PRIMARY KEY,
    TENANT_ID VARCHAR2(14) NOT NULL,
    SCHEDULE_GROUP VARCHAR2(50) NOT NULL,
    SCHEDULE_NAME VARCHAR2(200) NOT NULL,
    OCCURRENCE_KEY VARCHAR2(200) NOT NULL,
    SCHEDULED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    STATUS VARCHAR2(32) NOT NULL,
    ATTEMPT_COUNT INTEGER DEFAULT 0 NOT NULL,
    CANCELLATION_REQUESTED VARCHAR(1) DEFAULT 'N' NOT NULL,
    VERSION NUMBER(19) DEFAULT 0 NOT NULL,
    CONSTRAINT UK_MY_EXEC_OCCURRENCE UNIQUE (TENANT_ID, SCHEDULE_GROUP, SCHEDULE_NAME, OCCURRENCE_KEY)
);

CREATE TABLE MY_BATCH_EXECUTION_LEASE (
    EXECUTION_ID VARCHAR2(36) PRIMARY KEY,
    OWNER_NODE VARCHAR2(100),
    LEASE_TOKEN NUMBER(19) DEFAULT 0 NOT NULL,
    EXPIRES_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    VERSION NUMBER(19) DEFAULT 0 NOT NULL
);

CREATE TABLE MY_BATCH_ATTEMPT (
    ATTEMPT_ID VARCHAR2(64) PRIMARY KEY,
    EXECUTION_ID VARCHAR2(36) NOT NULL,
    ATTEMPT_NO INTEGER NOT NULL,
    NODE_ID VARCHAR2(100) NOT NULL,
    LEASE_TOKEN NUMBER(19) NOT NULL,
    PID NUMBER(19),
    STARTED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    PROCESS_STARTED_AT TIMESTAMP WITH TIME ZONE,
    ENDED_AT TIMESTAMP WITH TIME ZONE,
    EXIT_CODE INTEGER,
    STATUS VARCHAR2(32) NOT NULL,
    FAILURE_REASON VARCHAR2(1000),
    HEARTBEAT_AT TIMESTAMP WITH TIME ZONE,
    CONSTRAINT UK_MY_ATTEMPT_NO UNIQUE (EXECUTION_ID, ATTEMPT_NO)
);

