spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update  # (create, update, validate, none 중 선택)
    show-sql: true  # SQL 로그 출력 여부


logging:
  level:
    root: info
    com.fastcampus.sns: DEBUG


jwt:
  secret:
    key: fastcampus_sns_service.secret_key
  token:
    expired:
      time: 6000000 #30 day